/*
 * Copyright (C) 2014 joe
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package com.jrgp.thadmin;

import java.util.ArrayList;
import org.slf4j.LoggerFactory;

/**
 *
 * @author joe
 */
public class MainWindow extends javax.swing.JFrame {

    ArrayList<TabBody> serverTabs;

    private final static org.slf4j.Logger LOGGER = LoggerFactory.getLogger(MainWindow.class);

    /**
     * Creates new form ServerTabs
     */
    public MainWindow() {
        initComponents();

        openFavoritesButton.setVisible(false);

        addKagButton.setIcon(Icons.getIcon(ServerType.KAG));
        addSoldatButton.setIcon(Icons.getIcon(ServerType.SOLDAT));

        IpCountry.Load();
        Conf.Load();
        FavoriteServers.Load();
        FavoriteServers.connectServers(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();
        addKagButton = new javax.swing.JButton();
        addSoldatButton = new javax.swing.JButton();
        openFavoritesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THD Admin");
        setMinimumSize(new java.awt.Dimension(700, 400));

        addKagButton.setText("Add KAG Tab");
        addKagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addKagButtonActionPerformed(evt);
            }
        });

        addSoldatButton.setText("Add Soldat Tab");
        addSoldatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSoldatButtonActionPerformed(evt);
            }
        });

        openFavoritesButton.setText("Favorites");
        openFavoritesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFavoritesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addKagButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSoldatButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(openFavoritesButton)
                .addContainerGap())
            .addComponent(Tabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addKagButton)
                    .addComponent(addSoldatButton)
                    .addComponent(openFavoritesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addKagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addKagButtonActionPerformed
        ServerType type = ServerType.KAG;
        TabBody tab = new TabBody(type, this);
        Tabs.addTab("Server", tab);
        fixTabs();
    }//GEN-LAST:event_addKagButtonActionPerformed

    private void addSoldatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSoldatButtonActionPerformed
        ServerType type = ServerType.SOLDAT;
        TabBody tab = new TabBody(type, this);
        Tabs.addTab("Server", tab);
        fixTabs();    }//GEN-LAST:event_addSoldatButtonActionPerformed

    private void openFavoritesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFavoritesButtonActionPerformed

    }//GEN-LAST:event_openFavoritesButtonActionPerformed

    public void addTab(TabBody tab, String title) {
        Tabs.addTab(title, tab);
        fixTabs();
    }

    public void fixTabs() {
        int tabcount = Tabs.getTabCount();
        for (int index = 0; index < tabcount; index++) {
            TabBody tab = (TabBody) Tabs.getComponentAt(index);
            String title = tab.getHostString();
            title = title.length() == 0 ? "Server" : title;
            title = title+(title.equals("Server") ? "" : (tab.isConnected() ? " (Connected)" : " (Disconnected)"));

            Tabs.setTabComponentAt(index, TabUtils.getTabLabel(tab.getType(), title, this, tab));
        }
    }

    public void killTab(TabBody component) {
        int tabcount = Tabs.getTabCount();
        int tabIndexToKill = -1;
        for (int index = 0; index < tabcount; index++) {
            if (component == (TabBody) Tabs.getComponentAt(index)) {
                tabIndexToKill = index;
                break;
            }
        }
        if (tabIndexToKill == -1) {
            LOGGER.error("Couldn't find index to kill tab");
            return;
        }
        component.HandleDisonnect();
        Tabs.removeTabAt(tabIndexToKill);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JButton addKagButton;
    private javax.swing.JButton addSoldatButton;
    private javax.swing.JButton openFavoritesButton;
    // End of variables declaration//GEN-END:variables
}
