package kag;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultCaret;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/*
 * Copyright (C) 2014 joe
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/**
 *
 * @author joe
 */
public class TabBody extends javax.swing.JPanel {
    private KagSocket Server = null;
    private boolean Connected = false;
    
    private final DefaultTableModel PlayerModel;
    
    /**
     * Creates new form TabBody
     */
    public TabBody() {
        Regexes.init();
        
        initComponents();

      //  DefaultCaret caret = (DefaultCaret)ConsoleLog.getCaret();
     //   caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
        PlayerModel = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player", "ID", "IP", "HWID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        
        PlayerTable.setModel(PlayerModel);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        HostBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PasswordBox = new javax.swing.JPasswordField();
        ConnectButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlayerTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsoleLog = new javax.swing.JTextPane();
        CommandBox = new javax.swing.JTextField();
        CommandButton = new javax.swing.JButton();

        jLabel1.setText("IP:port");

        HostBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HostBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        PasswordBox.setText("jPasswordField1");

        ConnectButton.setText("Connect");
        ConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectButtonActionPerformed(evt);
            }
        });

        PlayerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PlayerTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(PlayerTable);

        ConsoleLog.setEditable(false);
        jScrollPane2.setViewportView(ConsoleLog);

        CommandBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommandBoxActionPerformed(evt);
            }
        });

        CommandButton.setText("Run");
        CommandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommandButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HostBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConnectButton)
                        .addGap(0, 212, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CommandBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CommandButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HostBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(PasswordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConnectButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CommandBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CommandButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HostBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HostBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HostBoxActionPerformed

    private void CommandBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommandBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommandBoxActionPerformed

    private void ConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectButtonActionPerformed
        if (ConnectButton.getText().equals("Disconnect")) {
            HandleDisonnect();
        }
        else if (ConnectButton.getText().equals("Connect")) {
            System.out.println("clicked connect");
            HandleConnect();
        } 
    }//GEN-LAST:event_ConnectButtonActionPerformed
    private void SendCommand() {
        String command = CommandBox.getText().trim();
        CommandBox.setText("");
        
        if (command.length() == 0 || !Connected || Server == null) {
            return;
        }
        
        Server.sendCommand(command);
    }
    
    private void CommandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommandButtonActionPerformed
               SendCommand();
    }//GEN-LAST:event_CommandButtonActionPerformed

    private void PasswordBoxKeyTyped(java.awt.event.KeyEvent evt) {                                     
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            HandleConnect();
    }                                    

    private void CommandBoxKeyTyped(java.awt.event.KeyEvent evt) {                                    
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            HandleConnect();
    }   
    
    private void HandleConnect() {
        String IpPort = HostBox.getText();
        String Password = new String(PasswordBox.getPassword());
        
        String Host;
        Integer Port;
        
        String parts[] = IpPort.split(":");
        
        if (parts.length < 2 || IpPort.length() == 0 || Password.length() == 0) {
            JOptionPane.showMessageDialog(this, "You must appropriately fill out the password fields",
                    "Incomplete input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Host = parts[0];
        
        try {
            Port = Integer.parseInt(parts[1]);
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Port does not look like a number",
                    "Incomplete input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (Port < 1 || Port > 65000) {
            JOptionPane.showMessageDialog(this, "Port is not within a realistic range",
                    "Incomplete input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        System.out.println("passed checks");
        
        ConnectButton.setEnabled(false);
        
        Server = new KagSocket(this);
        
        Server.setDetails(Host, Password, Port);
        Server.execute();
    }        
    
    private void HandleDisonnect() {
        boolean success = Server.cancel(true);
        
        if (success)
            System.out.println("Cancelled worker");
        else
            System.out.println("Failed to cancel worker");
    }
    
    public void addConsoleLine(String line, String type) {
        class StyledText {
            SimpleAttributeSet style;
            String text;
            public  StyledText(SimpleAttributeSet style, String text) {
                this.text = text;
                this.style = style;
            }
        }
        
        StyledDocument doc = ConsoleLog.getStyledDocument();
        
        List<StyledText> words = new ArrayList<>();
        
        Matcher match;
        
        SimpleAttributeSet style;
        
        if (type.equals("connect")) {
            style = new SimpleAttributeSet();
            StyleConstants.setForeground(style, Color.GREEN);
            StyleConstants.setBold(style, true);
            words.add(new StyledText(style, line));
        }
        else if (type.equals("disconnect")) {
            style = new SimpleAttributeSet();
            StyleConstants.setForeground(style, Color.RED);
            StyleConstants.setBold(style, true);
            words.add(new StyledText(style, line));
        }
        else if (type.equals("console")) {
            
            if ((match = Regexes.lineRconConnect.matcher(line)) != null && match.find()) {
                style = new SimpleAttributeSet();
                StyleConstants.setBold(style, true);
                StyleConstants.setForeground(style, Color.darkGray);
                words.add(new StyledText(style, match.group(1)));
                
                words.add(new StyledText(null, " TCP RCON Connection from "));
                
                style = new SimpleAttributeSet();
                StyleConstants.setForeground(style, Color.BLACK);
                StyleConstants.setBold(style, true);
                words.add(new StyledText(style, match.group(2)));
                
                words.add(new StyledText(null, " is now authenticated"));
            }
            else if ((match = Regexes.linePlayerSpeak.matcher(line)) != null && match.find()) {
                style = new SimpleAttributeSet();
                StyleConstants.setBold(style, true);
                StyleConstants.setForeground(style, Color.darkGray);
                words.add(new StyledText(style, match.group(1)));
                
                words.add(new StyledText(null, " "));
                
                style = new SimpleAttributeSet();
                StyleConstants.setForeground(style, Color.BLACK);
                StyleConstants.setBold(style, true);
                words.add(new StyledText(style, match.group(2)));
                
                words.add(new StyledText(null, " "));
                
                style = new SimpleAttributeSet();
                StyleConstants.setForeground(style, Color.GRAY);
                words.add(new StyledText(style, match.group(3)));                
            }
            else if ((match = Regexes.lineRconCommand.matcher(line)) != null && match.find()) {
                
                // I do not care when people run /players
                if (match.group(3).equals("/players")) {
                    return;
                }
                
                style = new SimpleAttributeSet();
                StyleConstants.setBold(style, true);
                StyleConstants.setForeground(style, Color.darkGray);
                words.add(new StyledText(style, match.group(1)));
                
                words.add(new StyledText(null, " RCON command from "));
                
                style = new SimpleAttributeSet();
                StyleConstants.setForeground(style, Color.BLACK);
                StyleConstants.setBold(style, true);
                words.add(new StyledText(style, match.group(2)));
                
                words.add(new StyledText(null, ": "));
                
                style = new SimpleAttributeSet();
                StyleConstants.setForeground(style, Color.BLACK);
                StyleConstants.setBold(style, true);
                words.add(new StyledText(style, match.group(3)));                
            }
            else if ((match = Regexes.lineConsole.matcher(line)) != null && match.find()) {
                
                // don't care about empty shiz or other stuff we know happens
                if (match.group(2).trim().length() == 0 || match.group(2).equals(" /players")) {
                    return;
                }
                
                style = new SimpleAttributeSet();
                StyleConstants.setBold(style, true);
                StyleConstants.setForeground(style, Color.darkGray);
                words.add(new StyledText(style, match.group(1)));
                
                words.add(new StyledText(null, " "));
                
                style = new SimpleAttributeSet();
                StyleConstants.setForeground(style, Color.GRAY);
                words.add(new StyledText(style, match.group(2)));
            }
            
            // something our regexen didn't pickup... gray that fucker out
            else {
                style = new SimpleAttributeSet();
                StyleConstants.setForeground(style, Color.GRAY);
                words.add(new StyledText(style, line));
            }
        }
        
        words.add(new StyledText(null, "\n"));
        
        try {
            for (StyledText text : words) {
                doc.insertString(doc.getLength(), text.text, text.style);
            }
        }
        catch (BadLocationException e) {
            
        }
    }
    
    public void onConnect() {
        ConnectButton.setText("Disconnect");
        HostBox.setEditable(false);
        PasswordBox.setEditable(false);
        CommandBox.setEditable(true);
        CommandButton.setEnabled(true);
        Connected = true;
        ConnectButton.setEnabled(true);
        addConsoleLine("Connected", "connect");
    }

    public void onDisconnect() {
        ConnectButton.setText("Connect");
        HostBox.setEditable(true);
        PasswordBox.setEditable(true);
        CommandBox.setEditable(false);
        CommandBox.setText("");
        CommandButton.setEnabled(false);
        Connected = false;
        ConnectButton.setEnabled(true);
        addConsoleLine("Disconnected..", "disconnect");
        drawPlayers(new ArrayList<>());
    }
    
    public void drawPlayers(List<KagPlayer> players) {
        PlayerModel.setRowCount(0);
        for (KagPlayer player : players) {
            PlayerModel.addRow(new Object[]{
                player.name,
                player.id,
                player.ip,
                player.hwid
            });
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CommandBox;
    private javax.swing.JButton CommandButton;
    private javax.swing.JButton ConnectButton;
    private javax.swing.JTextPane ConsoleLog;
    private javax.swing.JTextField HostBox;
    private javax.swing.JPasswordField PasswordBox;
    private javax.swing.JTable PlayerTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
